<?php
// auto-generated by sfPropelAdmin
// date: 2007/08/01 14:36:57
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('list'), 'host/list?id='.$host->getId(), array (
  'class' => 'sf_admin_action_list',
)) ?></li>
  <li><?php echo submit_tag(__('save'), array (
  'name' => 'save',
  'class' => 'sf_admin_action_save',
)) ?></li>
  <li><?php echo submit_tag(__('save and list'), array (
  'name' => 'save_and_list',
  'class' => 'sf_admin_action_save_and_add',
)) ?></li>
</ul>
