<?php
// auto-generated by sfPropelAdmin
// date: 2007/08/01 14:36:57
?>
<?php echo form_tag('host/saveserviceparameters', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($host, 'getId') ?>

<?php echo service_input_list($services); ?>

<?php include_partial('serviceparameters_actions', array('host' => $host)) ?>

</form>
